### ISSUE TITLE
Detach?

### ISSUE THREAD

**Issue by prologic** [0xc0d/vessel#1]
Hey @0xc0d 👋

I'm also writing a container runtime, but a little more seriously than a toy. Was wondering whether you ever managed to get detach working so you could run a container detached from the controlling terminal?

Thanks!

**Comment by 0xc0d** [comment]
Hi @prologic,

Thank you for your question. I just realized that my implementation was not alright.
For detaching you need to release the underneath process from the parent.

**Comment by prologic** [comment]
> Hi @prologic,
> 
> Thank you for your question. I just realized that my implementation was not alright. For detaching you need to release the underneath process from the parent.

Yup 😅 Some of my code was/is inspired by your project and I realized this too, hence why I asked. Unfortunately it doens't seem to be as easy as "separate the process from the parent" 😅

**Comment by prologic** [comment]
Hi @0xc0d 👋 I wanted to let you know that I eventually managed to fix support for running containers detached with a `-d/--detach` flag. See [this PR](https://git.mills.io/prologic/box/pulls/21) and attached screenshot showing this working 👌

In the end I had to:

1. Ensure important devices such as `/dev/null` were available in the container's filesystem. So I borrowed some code from [GoNix](https://git.mills.io/prologic/gonix) to do this `CreateDevices()` once we're inside the new container's namespace and filesystem.
2. Set the SysProcAttr(s) `Pgid: 0` and `Setpgid: true` in the parent process of the container -- That is `run.go` for me (_probably similar for you_)
3. Ensure that the container process (_the forked or init process, which for me is in `fork.go` and ends up being the parent process, or supervisor of the actual binary being run in the container `/proc/self/exe`) **actually** waits on the container process. It is in fact the parent process, the one that sets things up (`gun.go` for me) where you can start and essentially terminate, but obviously not without setting up the mentioned SysProgAttr(s) above so the process has its own process group and session.

Finally I _think_ its also important not to attach the terminal's standard fds to any part of the process either.

**Comment by prologic** [comment]
<img width="1242" alt="Screen Shot 2022-09-19 at 01 44 20" src="https://user-images.githubusercontent.com/1290234/190933401-2ff759b8-cf0f-49a6-8d92-87bbe21b4e31.png">
